# analysis/validation/run_irf_comparison.py
from matplotlib import pyplot as plt
import numpy as np

from analysis.scenario_irf import scenario_irf_exog
from analysis.validation.simulate_data import (
    simulated_panel_full_system, simulated_panel, simulate_var2_fixed )
from analysis.estimate_var import fit_country_varx_TVP, fit_country_varx_VAR
from analysis.var_spec import VARSpec
from models.config import EXTERNAL_VARS, DOMESTIC_VARS, FOREIGN_VARS

# DEBUG FLAG
flag_debug = False

# --- simulate data
df_sim, _ = simulate_var2_fixed(T=2000)
panel = simulated_panel(df_sim, country="SIM")

# --- simulate full system
# panel = simulated_panel_full_system(T=3000)

# estimate_var.fit_country_varx_TVP()
#   get X,Y from panel, standardize
#   -> tvp_var_with_exog_and_var_prior()
#        -> VAR()
#        -> build_kalman_prior_cov()
#        get beta0, P0
#        -> tvp_var_with_exog(beta0,P0)
R = 0.01 # R = .001 gives better exogenous irf fit, worse endogenous
lam = 1.0

spec = VARSpec(
    endog_vars=DOMESTIC_VARS,
    exog_vars=FOREIGN_VARS + EXTERNAL_VARS,
    include_const=False,
    demean=False,
    standardize=True,
    p=1,
)

res_tvp = fit_country_varx_TVP(panel, "SIM", spec, R=R, lam=lam, prior_var=True)
res_var = fit_country_varx_VAR(panel, "SIM", spec)

# A_var and res_var.coefs rows are equations
A_var = res_var.coefs
beta_tvp_final = res_tvp.beta_path[-1]     # (m, k)
m, k = beta_tvp_final.shape
from analysis.validation.compare_betas import extract_A_blocks_from_beta
# A_tvp rows are equations
A_tvp = extract_A_blocks_from_beta(beta_tvp_final, p=spec.p, k=k)

print("max abs A diff:", np.max(np.abs(A_var - A_tvp)))

# Force TVP to use VAR coefficients exactly
if flag_debug:
    # Need transpose of A_var[0], A_var[1], ...
    beta_override = np.vstack([
        np.vstack(A_var),           # (p*k, k)
        res_var.coefs_exog.T         # (q, k)
    ])
    res_tvp.beta_path[-1] = beta_override

# ----- IRF comparison using Streamlit code (this is the diagnostic)
# (A) Endogenous IRFs
H = 12
t0 = -1

res_tvp.sigma_u = res_var.sigma_u.copy()
from models.irf import irf_var_consistent, irf_from_tvp

# irf_var[h, response_idx, impulse_idx]
irf_var = irf_var_consistent(res_var, H)
irf_tvp = irf_from_tvp(res_tvp, H, t0=t0)
# rows or irf_typ are equatiosn
# irf_var = res_var.irf(H)
# irf_tvp = res_tvp.irf(H=H, t0=t0)

h = 1
print("VAR h=1 matrix:\n", irf_var[h])
print("TVP h=1 matrix:\n", irf_tvp[h])
print("max abs matrix diff:", np.max(np.abs(irf_var[h] - irf_tvp[h])))
print("max abs transpose diff:", np.max(np.abs(irf_var[h].T - irf_tvp[h])))
# print("VAR Dy diag:", np.diag(res_var.Dy))
# print("TVP Dy diag:", np.diag(res_tvp.Dy))

# irf_var is (H+1, k, k) in standardized units
Dy = res_var.Dy
Dy_inv = np.linalg.inv(Dy)
irfsi_var = np.empty_like(irf_var)
for h in range(H + 1):
    # irfsi_var[h].T is closest to MATLAB
    # irf_var cols are equations: input -> divide by Dy -> irf -> multiply by Dy
    irfsi_var[h] = Dy_inv @ irf_var[h] @ Dy

# r = res_var.names.index("GDP_YoY")
r = spec.endog_vars.index("GDP_YoY")
i = spec.endog_vars.index("CPI_YoY")

print("VARi raw:", irfsi_var[1:5, i, r])
print("TVP raw:", irf_tvp[1:5, i, r])
print("VAR/TVP raw:", irf_tvp[1:5, i, r] / irfsi_var[1:5, i, r])

# columns are equations
plt.plot(irfsi_var[:, i, r], label="VAR (innovation)")
plt.plot(irf_tvp[:, i, r], label="TVP (innovation)")
plt.legend()
plt.title("irf for res_var, res_tvp")
plt.show()

shock_var = "ENSO"

# DEBUG
if flag_debug:
# 1. Force same coefficients
#      res_var.coefs rows are equations, need transpose
    beta_override = np.vstack([
        np.vstack(res_var.coefs),
        res_var.coefs_exog.T
    ])
    res_tvp.beta_path[-1] = beta_override
    # 2. Force same endogenous state
    res_tvp.endog = res_var.endog.copy()
    # 3. Force same exogenous state
    res_tvp.exog = res_var.exog.copy()
    # 4. Force same shock scaling
    shock_percentile = 84
    shock_idx = res_tvp._exog_columns.index(shock_var)
    shock_series = res_var.exog[:, shock_idx]
    shock_size = np.nanpercentile(shock_series, shock_percentile)

# (B) Exogenous scenario IRFs (your main concern)
diff_tvp = scenario_irf_exog( res_tvp, shock_var=shock_var, H=H, t0=t0 )
diff_var = scenario_irf_exog( res_var, shock_var=shock_var, H=H, t0=t0 )

resp_idx = list(res_tvp.names).index("GDP_YoY")

plt.plot(diff_var[:, resp_idx], "--", label="VAR")
plt.plot(diff_tvp[:, resp_idx], "-", label="TRP")
plt.legend()
plt.title("VAR, TVP generated by scanario_irf_exog()")
plt.show()
